version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogAppDataBase
      MYSQL_USER: jakub
      MYSQL_PASSWORD: user
    ports:
      - "2115:3306"
    volumes:
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql

